spring:
  rabbitmq:
    username: test
    password: 123456
    host: 192.168.10.23
    port: 5672
    virtual-host: /yingjftest
  cloud:
    stream:
      bindings:
        my-input-channel:
          destination: my-queue
          binder: rabbit
      rabbit:
        bindings:
          my-input-channel:
            consumer:
              bindingRoutingKey: my-queue
