spring:
  rabbitmq:
    username: test
    password: 123456
    host: 192.168.10.23
    port: 5672
    virtual-host: /yingjftest
  cloud:
    stream:
      bindings:
        my-input-channel:
          destination: my-queue
          binder: rabbit
          group: my-queue-group
        my-ack-input-channel:
          destination: my-ack-queue
          binder: rabbit
          group: my-ack-queue-group
        my-lazy-input-channel:
          destination: my-lazy-queue
          binder: rabbit
          group: my-lazy-queue-group
      rabbit:
        bindings:
          my-input-channel:
            consumer:
              bindingRoutingKey: my-queue
          my-ack-input-channel:
            consumer:
              acknowledge-mode: manual
              bindingRoutingKey: my-ack-queue
          my-lazy-input-channel:
            consumer:
              bindingRoutingKey: my-lazy-queue
