spring:
  cloud:
    stream:
      bindings:
        my-output-channel:
          destination: my-queue
          binder: mybinders
        my-ack-output-channel:
          destination: my-ack-queue
          binder: mybinders
      rabbit:
        bindings:
          my-output-channel:
            producer:
              bindingRoutingKey: my-queue
          my-ack-output-channel:
            producer:
              bindingRoutingKey: my-ack-queue
      binders:
        mybinders:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: test
                password: 123456
                host: 192.168.10.23
                port: 5672
                virtual-host: /yingjftest
      default-binder: mybinders

